DROP TABLE IF EXISTS public.profiles;
DROP TABLE IF EXISTS public.companies;
DROP TABLE IF EXISTS public.city_halls;
DROP TABLE IF EXISTS public.addresses;

--Creating addresses table

CREATE TABLE IF NOT EXISTS public.addresses
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default",
    street character varying(255) COLLATE pg_catalog."default",
    zip character varying(30) COLLATE pg_catalog."default",
    tag character varying(30) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.addresses
    OWNER to admin;