CREATE TABLE IF NOT EXISTS public.profiles
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    civility character varying(10) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" UNIQUE NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(30) COLLATE pg_catalog."default" UNIQUE NOT NULL,
    address_id integer,
    CONSTRAINT fk_profiles_addresses FOREIGN KEY (address_id)
        REFERENCES public.addresses (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT profiles_civility_check CHECK (civility::text = ANY (ARRAY['MR'::character varying, 'MRS'::character varying, 'MISS'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.profiles
    OWNER to admin;