DROP TABLE IF EXISTS public.roles;
DROP TABLE IF EXISTS public.permissions;

CREATE TABLE IF NOT EXISTS public.permissions
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL UNIQUE
)
TABLESPACE pg_default;
ALTER TABLE IF EXISTS public.permissions
    OWNER to admin;



CREATE TABLE IF NOT EXISTS public.roles
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL UNIQUE,
    CONSTRAINT roles_name_check CHECK (name::text = ANY (ARRAY['ROLE_AGENT'::character varying, 'ROLE_ADMIN'::character varying, 'ROLE_USER'::character varying]::text[]))
)
TABLESPACE pg_default;
ALTER TABLE IF EXISTS public.permissions
    OWNER to admin;



DROP TABLE IF EXISTS public.role_permissions;
CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT role_permissions_pk PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission FOREIGN KEY (permission_id)
        REFERENCES public.permissions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_permission_role FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;
ALTER TABLE IF EXISTS public.role_permissions
    OWNER to admin;


INSERT INTO public.permissions (description, is_active, name) VALUES
('Can create agent', true, 'AGENT_CREATE'),
('Can read agent', true, 'AGENT_READ'),
('Can update agent', true, 'AGENT_UPDATE'),
('Can delete agent', true, 'AGENT_DELETE'),

('Can create admin', true, 'ADMIN_CREATE'),
('Can read admin', true, 'ADMIN_READ'),
('Can update admin', true, 'ADMIN_UPDATE'),
('Can delete admin', true, 'ADMIN_DELETE'),

('Can create user', true, 'USER_CREATE'),
('Can read user', true, 'USER_READ'),
('Can update user', true, 'USER_UPDATE'),
('Can delete user', true, 'USER_DELETE'),

('Can create profile', true, 'PROFILE_CREATE'),
('Can read profile', true, 'PROFILE_READ'),
('Can update profile', true, 'PROFILE_UPDATE'),
('Can delete profile', true, 'PROFILE_DELETE'),

('Can create declaration', true, 'DECLARATION_CREATE'),
('Can read declaration', true, 'DECLARATION_READ'),
('Can update declaration', true, 'DECLARATION_UPDATE'),
('Can delete declaration', true, 'DECLARATION_DELETE'),

('Can create request', true, 'REQUEST_CREATE'),
('Can read request', true, 'REQUEST_READ'),
('Can update request', true, 'REQUEST_UPDATE'),
('Can delete request', true, 'REQUEST_DELETE');

INSERT INTO public.roles (description, is_active, name) VALUES
('Administrator with full access', true, 'ROLE_ADMIN'),
('Regular user with limited access', true, 'ROLE_USER'),
('Support agent with moderate access', true, 'ROLE_AGENT');

INSERT INTO public.role_permissions (role_id, permission_id) VALUES
-- ROLE_ADMIN Permissions (Full Access)
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'AGENT_CREATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'AGENT_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'AGENT_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'AGENT_DELETE')),

    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'ADMIN_CREATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'ADMIN_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'ADMIN_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'ADMIN_DELETE')),

    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'USER_CREATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'USER_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'USER_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'USER_DELETE')),

    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'PROFILE_CREATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'PROFILE_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'PROFILE_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'PROFILE_DELETE')),

    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_CREATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_DELETE')),

    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_CREATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_ADMIN'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_DELETE')),

-- ROLE_USER Permissions (Typically focused on their own profile, declarations, and requests)
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'PROFILE_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'PROFILE_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_CREATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_DELETE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_CREATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_USER'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_DELETE')),

-- ROLE_AGENT Permissions (Access related to managing users, declarations, and requests)
    ((SELECT id FROM public.roles WHERE name = 'ROLE_AGENT'), (SELECT id FROM public.permissions WHERE name = 'USER_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_AGENT'), (SELECT id FROM public.permissions WHERE name = 'PROFILE_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_AGENT'), (SELECT id FROM public.permissions WHERE name = 'PROFILE_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_AGENT'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_AGENT'), (SELECT id FROM public.permissions WHERE name = 'DECLARATION_UPDATE')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_AGENT'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_READ')),
    ((SELECT id FROM public.roles WHERE name = 'ROLE_AGENT'), (SELECT id FROM public.permissions WHERE name = 'REQUEST_UPDATE'));