DROP TABLE IF EXISTS public.activation_codes;

CREATE TABLE IF NOT EXISTS public.activation_codes
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    ip_address character varying(100) COLLATE pg_catalog."default",
    is_used boolean NOT NULL DEFAULT false,
    expire_at timestamp(6) without time zone NOT NULL,
    profile_id INTEGER NOT NULL,
    type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fk_profile_activation_code FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
    MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE CASCADE,
    CONSTRAINT profiles_type_check CHECK (type::text = ANY (ARRAY['EMAIL'::character varying, 'PHONE'::character varying]::text[]))
)
TABLESPACE pg_default;
ALTER TABLE IF EXISTS public.activation_codes
    OWNER to admin;